name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout master brancher
    
    - id: commit
      uses: prompt/actions-commit-hash@v3
    
    - id: time
      name: Get Time Stamp
      uses: nanzm/get-time-action@v2.0
      with:
        # linux time zone
        timeZone: UTC+8 # optional, default is UTC
        # timestamp format
        format: "YYYYMMDDHHmmss" # optional, default is YYYY-MM-DD HH:mm:ss

    - name: Build the Docker image
      env: 
        tag: "v1-${{ steps.time.outputs.time }}-${{ steps.commit.outputs.short }}"
      run: |
        docker build . --file Dockerfile --tag wchstu/dind:$tag
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} 
        docker push wchstu/dind:$tag
        docker tag wchstu/dind:$tag wchstu/dind:latest
        docker push wchstu/dind:latest
        docker logout
